version: '2'
services:
  app:
    ports:
      - "3000:3000"
      restart: always
    environment:
      DB_USER: rootuser
      DB_NAME: testassesment
      DB_PASSWORD: root
      DB_HOST: 127.0.0.1 

  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testassesment
      MYSQL_USER: rootuser
      MYSQL_PASSWORD: root

volumes:
  mysql-data:

