# syntax=docker/Dockerfile:1

FROM node:12.18.1s
ENV NODE_ENV=production

WORKDIR /online examination/app

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install --production
EXPOSE 3000
COPY . .

CMD [ "node", "server.js" ]